INSPECTIT-2450: Adapt the workshop repository
inspectit-labs/workshop pull request #2
Opened 2017-07-07 14:56 UTC by birdy81

Move the DVD related files to own directory, create directory for petstore files and make it default workshop.

2017-07-31 11:51 UTC, ivansenic requested changes

2017-07-31 11:51 UTC, ivansenic commented on PET_Clinic/PET_BUSINESS_TRANSACTIONS.md
> +Once a business context has been created, it is opened in the editor. Now, we have to specify the application definition. In order to correlate data to an application **application mappings** are use
Once the application has been created..

Next sentence is also confusing, not sure what application definition is.. I would remove this sentence and go for mappings right away..

2017-07-31 11:51 UTC, ivansenic commented on PET_Clinic/PET_BUSINESS_TRANSACTIONS.md
> +We know that each microservice pf the Petclinic application is running on different ports. Therefore, a **HTTP Server Port Matching** should be created which matches all requests on a specific port t
each microservice **pf** -> of

_You can check this by navigating to the *Data Explorer View* of the api-gateway agent._ I think this is only visible in the invocation sequences, maybe add this info..

2017-07-31 11:51 UTC, ivansenic commented on PET_Clinic/PET_BUSINESS_TRANSACTIONS.md
> +Like a application definition, a business transaction definition consists of **business transaction mappings** which are used to correlate data to a business transaction.
Like **the**

2017-07-31 11:51 UTC, ivansenic commented on PET_Clinic/PET_BUSINESS_TRANSACTIONS.md
> +As before, create an **URI Matcher** which accepts all data where the URI starts with the value ```/api/customer/owners```. Press ```CTRL + S``` to save the changes. And that's it.
an **URI Matcher** which **maps all requests** where URI starts with..

2017-07-31 11:51 UTC, ivansenic commented on PET_Clinic/PET_BUSINESS_TRANSACTIONS.md
> +Second, we would like to see all requests that are related to static resources. Create a new business tracsaction with the name "Static Resources". As before, create an **URI Matcher** which accepts
Here you can say that static resources are all requests that have URI ending in .js / .css / etc, thus we will use URI regex matcher..

2017-07-31 11:51 UTC, ivansenic commented on PET_Clinic/PET_BUSINESS_TRANSACTIONS.md
> +Third, we still have requests that are not mapped to a Business Transaction. Thus, we would like to dynamically extract the name of the business transaction depending on the **URI**. As before, creat
Need to described that dynamic extraction is there to allow easier specification of the BTs, so that you don't have to do it manually for each BT..

2017-07-31 11:51 UTC, ivansenic commented on PET_Clinic/PET_BUSINESS_TRANSACTIONS.md
> +In the Business Transaction Mapping multiple rules can be used to define one business transaction. These rules are linked with OR conditions. In case AND conditions should be used enable the "advance
space too much between into "Edit Owner"

Would be nice to explain why you are doing this. You can explain that two BT are using same URi, thus we want to split them up.

2017-07-31 11:51 UTC, ivansenic commented on PET_Clinic/PET_BUSINESS_TRANSACTIONS.md
> +When you go back to the Data Explorer View you might see that there is no Business Transaction with "Edit Owner" or "Get All Owner". This comes from the fact that the order of the Business Transactio
I think also dynamic one needs to be last

2017-07-31 11:51 UTC, ivansenic commented on PET_Clinic/PET_INSTRUMENTATION.md
> +
Can we first have something simple like plain class method matching?

2017-07-31 11:51 UTC, ivansenic commented on PET_Clinic/PET_INSTRUMENTATION.md
> +##### 3. Capture details of an pet owner
of a pet owner

2017-07-31 11:51 UTC, ivansenic commented on PET_Clinic/PET_INSTRUMENTATION.md
> +After the update make sure that the new configuration works. Check the *Data Explorer View* of the agents api-gateway and and see if new classes/methods/exceptions are instrumented.
2 times and

2017-07-31 11:51 UTC, ivansenic commented on README.md
> +The inspectIT workshops uses the open source application "Spring Petclinic Microservices". The Pet Clinic application is a rather simple application based on the SpringBoot (Every microservice is a S
I would not mention the original repo, seams not needed. For the second link I would wrap this URL in a link.

2017-08-03 14:34 UTC, birdy81 commented on PET_Clinic/PET_BUSINESS_TRANSACTIONS.md
> +Once a business context has been created, it is opened in the editor. Now, we have to specify the application definition. In order to correlate data to an application **application mappings** are use
I explained in more detail what is an application definition and an application mapping. I would like to keep it, as the tabs is named "Application Definition".

2017-08-03 14:37 UTC, birdy81 commented on PET_Clinic/PET_BUSINESS_TRANSACTIONS.md
> +We know that each microservice pf the Petclinic application is running on different ports. Therefore, a **HTTP Server Port Matching** should be created which matches all requests on a specific port t
done

2017-08-03 14:37 UTC, birdy81 commented on PET_Clinic/PET_BUSINESS_TRANSACTIONS.md
> +Like a application definition, a business transaction definition consists of **business transaction mappings** which are used to correlate data to a business transaction.
done

2017-08-03 14:41 UTC, birdy81 commented on PET_Clinic/PET_BUSINESS_TRANSACTIONS.md
> +As before, create an **URI Matcher** which accepts all data where the URI starts with the value ```/api/customer/owners```. Press ```CTRL + S``` to save the changes. And that's it.
done.

2017-08-04 11:13 UTC, birdy81 commented on PET_Clinic/PET_BUSINESS_TRANSACTIONS.md
> +Third, we still have requests that are not mapped to a Business Transaction. Thus, we would like to dynamically extract the name of the business transaction depending on the **URI**. As before, creat
Correct, I will add this.

2017-08-04 11:18 UTC, birdy81 commented on PET_Clinic/PET_BUSINESS_TRANSACTIONS.md
> +In the Business Transaction Mapping multiple rules can be used to define one business transaction. These rules are linked with OR conditions. In case AND conditions should be used enable the "advance
done.

2017-08-04 11:20 UTC, birdy81 commented on PET_Clinic/PET_BUSINESS_TRANSACTIONS.md
> +When you go back to the Data Explorer View you might see that there is no Business Transaction with "Edit Owner" or "Get All Owner". This comes from the fact that the order of the Business Transactio
I switched point 3 and 4

2017-08-04 11:23 UTC, birdy81 commented on PET_Clinic/PET_INSTRUMENTATION.md
> +##### 3. Capture details of an pet owner
done.

2017-08-04 11:23 UTC, birdy81 commented on PET_Clinic/PET_INSTRUMENTATION.md
> +After the update make sure that the new configuration works. Check the *Data Explorer View* of the agents api-gateway and and see if new classes/methods/exceptions are instrumented.
done.

2017-08-04 11:35 UTC, birdy81 commented on PET_Clinic/PET_INSTRUMENTATION.md
> +
Ok good idea. I put step 1 to step 3. So the first would be to capture only one method getOwnerDetails()

2017-08-04 11:38 UTC, birdy81 commented on README.md
> +The inspectIT workshops uses the open source application "Spring Petclinic Microservices". The Pet Clinic application is a rather simple application based on the SpringBoot (Every microservice is a S
wrapped both links...

2017-08-11 13:12 UTC, ivansenic approved these changes

2017-08-11 13:12 UTC, merged